### ISSUE TITLE
Font styles do not work on macOS

### ISSUE THREAD

**Issue by achabotl** [enthought/enable#404] opened 2020-06-09 22:00 UTC
Italic and bold fonts are no found on macOS. The cause is a case-sensitive check that the filename contains the string italic or bold. Fix incoming.

https://github.com/enthought/enable/blob/6cf525cbeefdf34dc6eac5e54d7a73f755ea79b1/kiva/fonttools/font_manager.py#L557

Here's a minimal example with the broken code.

```python
from kiva.fonttools import Font
from kiva.image import GraphicsContext
from kiva.constants import ITALIC, BOLD

gc = GraphicsContext((200, 200))

gc.set_font(Font('', size=24))
gc.set_text_position(30, 120)
gc.show_text("Hello World")

gc.set_font(Font('Georgia', size=24))
gc.set_text_position(30, 80)
gc.show_text("Hello World")

gc.set_font(Font('Georgia', size=24, style=ITALIC))
gc.set_text_position(30, 40)
gc.show_text("Hello World")


gc.save('text.png')
```

![text](https://user-images.githubusercontent.com/479013/84200935-1a712000-aa6d-11ea-9c15-701194b35f78.png)

**Comment by corranwebster** [comment] 2020-06-11 07:35
I think this may be a duplicate of #391.

**Comment by achabotl** [comment] 2020-06-11 15:25
Yes, it's same root cause.

**Closed** 2020-12-09 17:12 UTC
